### ISSUE TITLE
Connotations of "Update" and "Refresh"

### ISSUE THREAD

**Issue by jim-thomson** [usnistgov/NISTIR-8112#22]
MITRE:

Minor:

3.2.1.2 "Last Update":

"Last update" .... date and time .. last refreshed" may be confusing. To me, update implies a change whereas refresh implies rewriting with the same value.:

Based on the definition, I would change the title to "Last Refresh" or "Last Verified":

```


```

---

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by RGalluzzo** [comment]
Thanks for the suggestion. This makes sense, but plan to discuss the update a little further.
