### ISSUE TITLE
Reorder Accuracy Metadata Elements Section

### ISSUE THREAD

**Issue by jim-thomson** [usnistgov/NISTIR-8112#25]
MITRE:

Minor:

Section 3.2.1.3:

Unwinding Origin, Provider, etc. challenges the reader because these are both elements and values.:

Move Provenance to be first; it describes the most stable values and is the logical starting point. Then Accuracy follows, which is more dynamic / varying by attribute value. Last would be Currency, the most dynamic.:

```


```

---

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by RGalluzzo** [comment]
This suggestion makes sense. This is a larger change, so while we are accepting it at this point, we will not make the modification until the close of the comment period.
