### ISSUE TITLE
Acceptable Uses and Combinations

### ISSUE THREAD

**Issue by jim-thomson** [usnistgov/NISTIR-8112#28]
1:

:

Section 3.2.1.4 Acceptable Uses Element:

I can see a number of combinations of this Element which is not described as multivalued. For example, an attribute may be used for multiple authorizations, some of which are by another party. Does this mean Secondary Use is the value of is it just Authorization? Secondary Use's description includes "beyond initially divulged" but sort of assumes the original divulging was for authorization. That may not be the case. And what does No Further Disclosure mean when an attribute may flow from an Origin to a Provider to another Provider? Just who is not supposed to disclose it further?:

This has to be rethought, because it combines the attribute value's use and its dissemination. This may require two different elements.:

```


```

---

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by RGalluzzo** [comment]
We are going to provide this feedback to our privacy team and discuss how best to address it. Thanks for the input!
