### ISSUE TITLE
Some definitions have diverged from SP800-63-3 definitions

### ISSUE THREAD

**Issue by andrewhughes3000** [usnistgov/NISTIR-8112#39]
**Organization**:  ITIM Consulting

**Type**: 2

**Reference (Include section and paragraph number)**:  Section 3, para (many)

**Comment (Include rationale for comment)**:  Definitions in SP800-63-3 have been modified over time. This issue is a reminder to re-synchronize definitions between the documents. For example these definitions in NISTIR 8112 no longer match 800-63-3 definitions: Assertion, Federation, Identity Provider (definition and case of acronym), Credential Service Provider, Relying Party, Attribute Claim, 

**Suggested Change**:

```
Update the definitions in NISTIR 8112 using NIST SP 800-63-3 as the source.

```

---

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by RGalluzzo** [comment]
Thanks for the comment. We will review the definitions again to make sure they are consistent with the most recent 800-63-3 content. Though, there may still be some deviation in language to directly support this document and reflect the language used throughout (e.g., user v. subscriber).
