### ISSUE TITLE
'Trust Time' is not defined

### ISSUE THREAD

**Issue by andrewhughes3000** [usnistgov/NISTIR-8112#40]
**Organization**: 2

**Type**: 

**Reference (Include section and paragraph number)**: section 2

**Comment (Include rationale for comment)**: 'Trust Time' is not defined in the definitions section

**Suggested Change**:

```
Please add a definition for 'trust time'

```

---

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by RGalluzzo** [comment]
Thanks for the comment. We will include a definition in our updates.
