### ISSUE TITLE
naming of metadata categories: "Attribute Value Metadata" versus "..."

### ISSUE THREAD

**Issue by JaapFrancke** [usnistgov/NISTIR-8112#47]
**Organization**:
 2
**Type**:
 
**Reference (Include section and paragraph number)**:
 1.2
**Comment (Include rationale for comment)**:
 Intuitively, people speak of 'attribute metadata'. The document describes two flavors of metadata.
While talking about 'attribute metadata', it will be easier to distinguish which sub-flavor is being discussed if each falvor has it's own term.

**Suggested Change**:
I think it wood be usefull to call the two flavors:
- Attribute Schema Metadata or Attribute Specification Metadata
- Attribute Value Metadata

```


```
 
---
 
Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by RGalluzzo** [comment]
Thanks for this comment. We had gone back and forth on titles for these different "flavors" but your recommendations were much better than what we had come up with!
