### ISSUE TITLE
Excutive summary not 100% consistent: Acceptable Uses

### ISSUE THREAD

**Issue by JaapFrancke** [usnistgov/NISTIR-8112#49]
**Organization**:
 
**Type**:
 
**Reference (Include section and paragraph number)**:
 
**Comment (Include rationale for comment)**:
 
**Suggested Change**:
Replace Acceptable Uses in executive summary with the 2 privacy attributes indicated in the 'core' document: Accepotable Primary uses and Acceptable Additional Uses.

```
 
---
 
Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by RGalluzzo** [comment]
We have made a few more edits, but these section should now be consistent.
