### ISSUE TITLE
Additional attributes  VerifierPerson and ChangePerson

### ISSUE THREAD

**Issue by JaapFrancke** [usnistgov/NISTIR-8112#51]
**Organization**:
2
 
**Type**:
 
**Reference (Include section and paragraph number)**:
3.2.2.1
3.2.1.3
 
**Comment (Include rationale for comment)**:
A nice to have...

For example in situations where RP and AP are roles within the same organisation, it may be useful to also indicate a specific staff-member that executed the verification of an attribute or changed the value of an attribute.

Example:
Within an enterprise there may be a process in which a ServiceDesk operator changes the email-address for an enduser.
By means of additional attributes it can be made transparent to the RP and/or enduser which operator applied the change.

 
**Suggested Change**:
Introduce
- ChangePerson as a Currency attribute - the person that submitted the new attribute value. This could be the enduser himself or could be a ServiceDesk operator, or ....
- VerifierPerson as an Accuracy attribute. 

 
---
 
Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by RGalluzzo** [comment]
This is a bit further into implementation details than we intended to delve in this paper.
