### ISSUE TITLE
Accuracy:validity metadata for self-asserted attributes

### ISSUE THREAD

**Issue by JaapFrancke** [usnistgov/NISTIR-8112#56]
**Organization**:
www.iWelcome.com
 
**Type**:
 
**Reference (Include section and paragraph number)**:
3.2.1.1
 
**Comment (Include rationale for comment)**:
The accuracy metadata are relevant or pertaining to determining if the attribute’s value is correct and belongs to a specific subject. 
The focus/bias of possible values for VerificationMethod is on the aspect of "belongs to a specific object". For attributes that are self-asserted but have not been verified, there is the notion of validation: some values can be known to be valid or not, regardless of the question whether or not the value belongs to the specific subject. A valid but unverified, self-asserted address has more value than an invalid, unverified, self-asserted address.

Having this attribute brings the value of not applying a verification process on invalid values.
 
**Suggested Change**:
Introduce Validation attribute in the 'accuracy' category. 
Possibly also a Validator attribute.
Validity has possible values "Valid", "Invalid", "Possibly valid", "Not validated".
Validator could be something like https://www.ups.com/content/us/en/bussol/browse/online_tools_us_address_validation.html.
Note that "Possibly valid" could be used to indicate situations where the value cannot be invalidated but cannot be confirmed to be valid with certainty.
 
---
 
Organization: 2 = Industry

**Comment by RGalluzzo** [comment]
This item seemed a little too subjective to include in the schema at this time. Logic and rules around "validity" of an attribute value may vary too widely to be consistently applied.

**Comment by JaapFrancke** [comment]
@RGalluzzo 
I understand your concern about subjectivity. However I think this can be resolved by adding a field to the Attribute Schema Metadata ("Validation method") that indicates the validation method that is applied for that field. This will make it transparent and less subjective. In a specific context, parties can agree on validation method. The AP can indicate the validation-method in the Attribute Schema Meta data.

Note that a similar approach could be applied for classification.
