### ISSUE TITLE
additional privacy metadata for parental consent

### ISSUE THREAD

**Issue by JaapFrancke** [usnistgov/NISTIR-8112#57]
**Organization**:
 
**Type**:
 
**Reference (Include section and paragraph number)**:
 
**Comment (Include rationale for comment)**:
In case a consent is given for usage of a minor's data, this consent may not be given by the subject himself, but by one of his parents.

It makes sense to capture this in the metadata for transparancy and auditing purposes.

 
**Suggested Change**:

Introduce a "grantor" privacy metadata attribute that holds information about who granted the consent when different from the subject-user.

(I'm not a native speaker of the english language, I hope i express myself clearly)

```
 
---
 
Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by RGalluzzo** [comment]
adding "parental" as a recommended value for 'consent'.
