### ISSUE TITLE
Description for "Acceptable Uses" speaks of additional uses

### ISSUE THREAD

**Issue by JaapFrancke** [usnistgov/NISTIR-8112#62]
**Organization**:
 
**Type**:
 
**Reference (Include section and paragraph number)**:
3.2.1.4
 
**Comment (Include rationale for comment)**:
Description for "Acceptable Uses" speaks of additional uses.  It's not clear in addition to what.
I think this is a remnant of previous version of the report that had primary and additional uses.

 
**Suggested Change**:

 
---
 
Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by RGalluzzo** [comment]
Nice catch! thanks!
